export enum DOCUMENT_TYPES {
    COMMERCIAL_INVOICE = '380',
    CREDIT_NOTE = '381',
    CORRECTED_INVOICE = '384',
    SELF_BILLED_INVOICE = '389',
    SELF_BILLED_CREDIT_NOTE = '261',
    PREPAYMENT_INVOICE = '386',
    INVOICE_INFORMATION = '751'
}
